name: Dispatch build to Jetstream cluster
on:
  push: {}
  workflow_dispatch: {}
jobs:
  jsbuild:
    env:
      NAMESPACE: testbuild
      PVC: rstudio-r-libraries-pvc
    runs-on: ubuntu-latest
    outputs:
      prefix: ${{ steps.prefix.outputs.prefix }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install k8s dependency
        run: python -m pip install kubernetes
      - uses: actions/checkout@v2
        with:
          #token: ${{ secrets.PAT }}
          persist-credentials: true
      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG}}" > ~/.kube/config
      - shell: bash
        run: bash -c "bash dispatch_loop.sh -n $NAMESPACE -c $PVC & sleep 30 && bash cleanup_loop.sh -n $NAMESPACE -c $PVC & sleep 60 && bash commit.sh & sleep 60 && bash update_lists.sh
        continue-on-error: true
      - shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "End of round"
          git push